import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/NavBar";
import Quiz from "../components/Quiz";
import { useAppContext } from "../context/state";

export default function Home() {
  const mycontext = useAppContext();

  return (
    <div className= "h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <h1> Hero's Journey</h1>
      <Quiz />
    </div>
  );
}

/* 
- global state 
- each answer button will be agree - a, slightly agree -b 
- each time the button is selected it adds a score
- if 
*/
